### ISSUE TITLE
[MISSING] - Adding kotlin-android-extensions under gradle

### ISSUE THREAD

**Issue by sriharigr** [udacity/andfun-kotlin-color-my-views#10]
Hi all,

I was facing an issue while importing a view based on the id as one of the plugins wasn't added in the gradle file. I might have missed it or it wasn't mentioned in the tutorial, not sure. Thought it would save some time for others. 
Below is the plugin that needs to be added.

_kotlin-android-extensions_

![Plugin to be added](https://user-images.githubusercontent.com/37204574/103072899-8a4f8e00-45ec-11eb-8e8f-760b84776af3.png)

**Comment by Dannark** [comment]
Worked like a charm, thanks!

**Comment by TheCodingArcher** [comment]
@sriharigr - you're an angel

**Comment by schapira** [comment]
thanks

**Comment by SudKul** [comment]
Thanks, we have incorporated your suggestion in the master branch in this [commit](https://github.com/udacity/andfun-kotlin-color-my-views/commit/2dfff9cf09eac5f3e2b2f0d9f7013251fc96e902).
