### ISSUE TITLE
[MISTAKE] The list items not defined.

### ISSUE THREAD

**Issue by RyanKoech** [udacity/andfun-kotlin-color-my-views#12]
https://github.com/udacity/andfun-kotlin-color-my-views/blob/07a063a705156f85291ec1ce35db865a29b0ffc5/app/src/main/java/com/example/android/colormyviews/MainActivity.kt#L39

**Comment by ritakialex** [comment]
Solution
https://github.com/udacity/andfun-kotlin-color-my-views/issues/11#issuecomment-816762363

**Comment by SudKul** [comment]
Not enough details to replicate the issue. 
Though, we have upgraded the `master` branch to use AndroidX in this [commit](https://github.com/udacity/andfun-kotlin-color-my-views/commit/2dfff9cf09eac5f3e2b2f0d9f7013251fc96e902).

We recommend you use the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors and submit a PR to help others avoid facing the same issue.
