### ISSUE TITLE
[MISTAKE] Instruction to add: <style name="whiteBox"...24sp@dimen...</style> INSTEAD OF <style name="whiteBox"...@dimen...</style>

### ISSUE THREAD

**Issue by ojedavidea** [udacity/andfun-kotlin-color-my-views#2]
https://github.com/udacity/andfun-kotlin-color-my-views/blob/36e039f89e8b5afd9edb1f8614b0142b6667c48d/app/src/main/res/values/styles.xml#L25

**Comment by SudKul** [comment]
Not enough details to replicate the issue. 
Though, we have upgraded the `master` branch to use AndroidX in this [commit](https://github.com/udacity/andfun-kotlin-color-my-views/commit/2dfff9cf09eac5f3e2b2f0d9f7013251fc96e902).

We recommend you use the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors and submit a PR to help others avoid facing the same issue.
